title: 'M3g4byt3'
description: "m3g4byt3's site for hackers, developers and script kiddies."
baseurl: "/"
url: "https://m3g4byt3.cf"

header_pages:
  - index.md
  - donate.md
  - about.md
  - contact.md

style: hacker

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
